spring.application.name=service-emergencias

# Línea clave: Usa el puerto dinámico que te asigne Render en internet
server.port=${PORT:8080}

# Conexión limpia y directa a PostgreSQL en Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always