# Nombre de la App
spring.application.name=service-emergencias
server.port=10000

# Configuración híbrida (Render en la nube / H2 Local para que no falle en IntelliJ)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.H2Dialect}

# Crear/Actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar mensajes de error detallados
server.error.include-message=always

# Consola H2 para pruebas locales (Opcional)
spring.h2.console.enabled=true