# Nombre de la App
spring.application.name=service-emergencias

# Base de datos local en ARCHIVO (No requiere instalación)
spring.datasource.url=jdbc:h2:file:./data/emergencias_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear/Actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Consola para que tú veas los datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Esto es vital para que la consola H2 sea accesible desde afuera si pruebas en red
spring.h2.console.settings.web-allow-others=true