# Nombre de la App
spring.application.name=service-emergencias

# Configuración para producción (Render/PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Crear/Actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Permitir que el Frontend (Ionic) se conecte desde cualquier lado
server.error.include-message=always